- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install node 12.X"
  shell: |
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt -y upgrade
    sudo apt install -y nodejs

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "copy files from CircleCI to server"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install 

- name: "build package"
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: "Migrations"
  shell: |
    cd /home/ubuntu/backend
    npm run migrations > migrations.txt
    cat migrations.txt
  register: migration_output

- debug:
    msg: "{{ migration_output.stdout_lines }}"

- name: "use pm2 to run the node server"
  shell: |
    cd /home/ubuntu/backend
    pm2 start ./dist/main.js
