version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "First Job"
  # The Frontend job
  frontend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm run build

  frontend-test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm run test

  backend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm run build

  backend-test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm run test
  audit-check-frontend:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm audit --audit-level=critical

  audit-check-backend:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm audit --audit-level=critical
  infrastructure_stack:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Infrastructure Stack
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/network.yml \
              --stack-name network-stack \
              --parameter-overrides EnvironmentName=prod

  backend-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Backend Infrastructure
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name backend-stack \
              --parameter-overrides ID=prod

  frontend-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Frontend Infrastructure
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name frontend-stack \
              --parameter-overrides ID=prod

workflows:
  default:
    jobs:
      # - hello-world
      # - frontend-lint:
      #     requires:
      #       - hello-world
      # - frontend-test:
      #     requires:
      #       - frontend-lint
      # - backend-lint:
      #     requires:
      #       - frontend-test
      # - backend-test:
      #     requires:
      #       - backend-lint
      # - audit-check-frontend:
      #     requires:
      #       - backend-test
      # - audit-check-backend:
      #     requires:
      #       - audit-check-frontend
      - cloudfront-infrastructure
      - frontend-infrastructure
      - backend-infrastructure
