version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "First Job"
  # The Frontend job
  frontend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm run build

  frontend-test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm run test

  backend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm run build

  backend-test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm run test
  audit-check-frontend:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm audit --audit-level=critical

  audit-check-backend:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm audit --audit-level=critical

  backend-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: echo "[all]" > ~/url.txt
      - run:
          name: Backend Infrastructure
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name backend-${CIRCLE_WORKFLOW_ID} \
              --parameter-overrides ID=backend-${CIRCLE_WORKFLOW_ID} \
              --region us-east-2
            aws ec2 describe-instances \
              --filters "Name=tag:aws:cloudformation:stack-name,Values=backend-${CIRCLE_WORKFLOW_ID}" \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --region us-east-2 \
              --output text >> ~/url.txt
      - run:
          name: Rollback
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID} \
              --region us-east-2
      - run:
          name: Install tar/gzip utility
          command: |
            yum -y install tar
            yum -y install gzip
      - persist_to_workspace:
          root: ~/
          paths:
            - url.txt

  frontend-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: echo "[all]" > ~/frontend.txt
      - run:
          name: Frontend Infrastructure
          command: |
            # aws cloudformation describe-stack-resources \
            #   --stack-name "${PRODUCTION_FRONTEND_STACK}" \
            #   --query 'StackResources[?LogicalResourceId==`WebsiteBucket`].PhysicalResourceId' \
            #   --region us-east-2 \
            #   --output text >> .circleci/ansible/frontend.txt
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name frontend-${CIRCLE_WORKFLOW_ID} \
              --parameter-overrides ID=frontend-${CIRCLE_WORKFLOW_ID} \
              --region us-east-2 \
              --output text >> ~/frontend.txt
      - run:
          name: Install tar/gzip utility
          command: |
            yum -y install tar
            yum -y install gzip
      - persist_to_workspace:
          root: ~/
          paths:
            - frontend.txt
      - run:
          name: Rollback
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID} \
              --region us-east-2
            aws cloudformation delete-stack --stack-name frontend-${CIRCLE_WORKFLOW_ID} \
              --region us-east-2
  add-backend-ip-to-inventory:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Install tar/gzip utility
          command: |
            yum -y install tar
            yum -y install gzip
      - attach_workspace:
          at: ~/
      - checkout
      - run:
          name: output of files
          command: |

            cat ~/frontend.txt
            cat ~/url.txt
      - run:
          name: Backend IP to ansible inventory
          command: |
            aws ec2 describe-instances \
              --filters "Name=tag:aws:cloudformation:stack-name,Values=backend-${CIRCLE_WORKFLOW_ID}" \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --region us-east-2 \
              --output text >> ~/inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory.txt
      - run:
          name: Rollback
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name frontend-${CIRCLE_WORKFLOW_ID} \
              --region us-east-2
            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID} \
              --region us-east-2

  config_backend_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - add_ssh_keys:
          fingerprints:
            - "5c:90:ff:21:74:44:c0:8c:98:bf:64:bf:a0:0e:c4:63"

      - run:
          name: output of files
          command: |
            cat ~/url.txt
      - run:
          name: Env Variables
          command: |
            echo "ENVIRONMENT=production" > backend/.env
            echo "NODE_ENV=production" >> backend/.env
            echo "TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS" >> backend/.env
            echo "TYPEORM_ENTITIES=$TYPEORM_ENTITIES" >> backend/.env
            echo "TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR" >> backend/.env
            echo "TYPEORM_CONNECTION=$TYPEORM_CONNECTION" >> backend/.env
            echo "TYPEORM_HOST=$TYPEORM_HOST" >> backend/.env
            echo "TYPEORM_PORT=$TYPEORM_PORT" >> backend/.env
            echo "TYPEORM_USERNAME=$TYPEORM_USERNAME" >> backend/.env
            echo "TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> backend/.env
            echo "TYPEORM_DATABASE=$TYPEORM_DATABASE" >> backend/.env
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            ansible-playbook -i ~/url.txt .circleci/ansible/playbook.yml

  database_migration:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Env Variables
          command: |
            echo "ENVIRONMENT=production" > backend/.env
            echo "NODE_ENV=production" >> backend/.env
            echo "TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS" >> backend/.env
            echo "TYPEORM_ENTITIES=$TYPEORM_ENTITIES" >> backend/.env
            echo "TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR" >> backend/.env
            echo "TYPEORM_CONNECTION=$TYPEORM_CONNECTION" >> backend/.env
            echo "TYPEORM_HOST=$TYPEORM_HOST" >> backend/.env
            echo "TYPEORM_PORT=$TYPEORM_PORT" >> backend/.env
            echo "TYPEORM_USERNAME=$TYPEORM_USERNAME" >> backend/.env
            echo "TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> backend/.env
            echo "TYPEORM_DATABASE=$TYPEORM_DATABASE" >> backend/.env
      - run:
          name: Database migration
          command: |
            cd backend
            npm install 
            npm run migrations
      - run:
          name: Rollback
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name frontend-${CIRCLE_WORKFLOW_ID} \
              --region us-east-2
            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID} \
              --region us-east-2

workflows:
  default:
    jobs:
      - hello-world
      # - frontend-lint:
      #     requires:
      #       - hello-world
      # - frontend-test:
      #     requires:
      #       - frontend-lint
      - backend-lint
          # requires:
          #   - frontend-test
      - backend-test:
          requires:
            - backend-lint
      - audit-check-frontend:
          requires:
            - backend-test
      - audit-check-backend:
          requires:
            - audit-check-frontend

      - backend-infrastructure:
          requires:
            - audit-check-frontend

      - frontend-infrastructure:
          requires:
            - backend-infrastructure
      - add-backend-ip-to-inventory:
          requires:
            - frontend-infrastructure
      - config_backend_infrastructure:
          requires:
            - add-backend-ip-to-inventory
      #- database_migration:
          #requires:
            #- config_backend_infrastructure
