version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "First Job"
  # The Frontend job
  frontend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm run lint

  frontend-test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm run test

  backend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm run lint

  backend-test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm run test

workflows:
  default:
    jobs:
      - hello-world
      - frontend-lint:
          requires: hello-world
      - frontend-test:
          requires: frontend-lint
      - backend-lint:
          requires: frontend-test
      - backend-test:
          requires: backend-lint
