version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "First Job"
  # The Frontend job
  frontend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm run build

  frontend-test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm run test

  backend-lint:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm run build

  backend-test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm run test
  audit-check-frontend:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd frontend && npm install

      - run:
          name: Testing
          command: cd frontend && npm audit --audit-level=critical

  audit-check-backend:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd backend && npm install

      - run:
          name: Testing
          command: cd backend && npm audit --audit-level=critical
  network-infrastructure-stack:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Network Infrastructure Stack
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/network.yml \
              --stack-name network-stack \
              --parameter-overrides EnvironmentName=prod \
              --region us-west-2
      - run:
          name: Rollback
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name network-stack


  backend-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Backend Infrastructure
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name backend-stack \
              --parameter-overrides ID=prod \
              --region us-west-2
      - run:
          name: Rollback
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name network-stack
            aws cloudformation delete-stack --stack-name backend-stack

  frontend-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Frontend Infrastructure
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --stack-name frontend-stack \
              --parameter-overrides ID=prod \
              --region us-west-2
      - run:
          name: Rollback
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name network-stack
            aws cloudformation delete-stack --stack-name backend-stack
            aws cloudformation delete-stack --stack-name frontend-stack

  cloudfront-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Cloudfront infrastructure
          command: |
            aws cloudformation deploy \
              --template-file ./.circleci/files/cloudfront.yml \
              --stack-name cloudfront-stack \
              --parameter-overrides ID=prod \              
              --no-fail-on-empty-changeset
      - run:
          name: Rollback
          when: on_fail
          command: |             
            aws cloudformation delete-stack --stack-name network-stack
            aws cloudformation delete-stack --stack-name backend-stack
            aws cloudformation delete-stack --stack-name frontend-stack
            aws cloudformation delete-stack --stack-name cloudfront-stack


workflows:
  default:
    jobs:
      # - hello-world
      # - frontend-lint:
      #     requires:
      #       - hello-world
      # - frontend-test:
      #     requires:
      #       - frontend-lint
      # - backend-lint:
      #     requires:
      #       - frontend-test
      # - backend-test:
      #     requires:
      #       - backend-lint
      # - audit-check-frontend:
      #     requires:
      #       - backend-test
      # - audit-check-backend:
      #     requires:
      #       - audit-check-frontend
      - network-infrastructure
            requires:
              - audit-check-frontend
      - backend-infrastructure
            requires:
              - network-infrastructure
      - frontend-infrastructure-stack
            requires:
              - backend-infrastructure
      - cloudfront-infrastructure
            requires:
              - frontend-infrastructure
